### ISSUE TITLE
Extension events not received

### ISSUE THREAD

**Issue by serpilliere** [psychon/x11rb#599] opened 2021-02-17 09:39 UTC
Hi!

I am trying to use the XFixes extension, and more precisely the SET_SELECTION_OWNER event notification. I have correct results in C code, but I am unable to get the notifications with x11rb. I am starting from the simple example https://github.com/enn/xcb-examples/blob/master/line_drawing.c

I added the following code to enable notification:
```C
	// init xfixes
	xcb_generic_error_t *error = 0;
	const xcb_query_extension_reply_t *reply = xcb_get_extension_data(c, &xcb_xfixes_id);
	if (!reply || !reply->present) {
		printf("no xfixes\n");
		exit(1);
	}
	xcb_xfixes_query_version_cookie_t xfixes_query_cookie = xcb_xfixes_query_version(c,
											 XCB_XFIXES_MAJOR_VERSION,
											 XCB_XFIXES_MINOR_VERSION);
	xcb_xfixes_query_version_reply_t *xfixes_query = xcb_xfixes_query_version_reply (c,
											 xfixes_query_cookie, &error);
	if (!xfixes_query || error || xfixes_query->major_version < 2) {
		free(error);
	}
	free(xfixes_query);

	xfixes_base = reply->first_event;
	printf("xfixes First event: %d\n", xfixes_base);

```

Now, I added the following code to the rust version to enable xfixes:
```rust
            conn.xfixes_select_selection_input(
                screen.root,
                x11rb::protocol::xproto::AtomEnum::PRIMARY.into(),
                xfixes::SelectionEventMask::SET_SELECTION_OWNER,
            )?;
            conn.xfixes_select_selection_input(
                screen.root,
                x11rb::protocol::xproto::AtomEnum::SECONDARY.into(),
                xfixes::SelectionEventMask::SET_SELECTION_OWNER,
            )?;

```

I looked at the generated x events on the C version:
```
client (6): QueryExtension(QueryExtensionRequest { name: [88, 70, 73, 88, 69, 83] })
Extension name: XFIXES
server (6): QueryExtension(QueryExtensionReply { sequence: 6, length: 0, present: true, major_opcode: 138, first_event: 87, first_error: 140 })
client (7): XfixesQueryVersion(QueryVersionRequest { client_major_version: 5, client_minor_version: 0 })
server (7): XfixesQueryVersion(QueryVersionReply { sequence: 7, length: 0, major_version: 5, minor_version: 0 })
client (8): XfixesSelectSelectionInput(SelectSelectionInputRequest { window: 94371843, selection: 1, event_mask: 1 })
client (9): XfixesSelectSelectionInput(SelectSelectionInputRequest { window: 94371843, selection: 2, event_mask: 1 })
..
```

and the Rust version:
```
...
client (13): QueryExtension(QueryExtensionRequest { name: [88, 70, 73, 88, 69, 83] })
Extension name: XFIXES
server (12): ReparentNotify(ReparentNotifyEvent { response_type: 21, sequence: 12, event: 96468992, window: 96468992, parent: 2098222, x: 0, y: 0, override_redirect: false })
server (12): MapNotify(MapNotifyEvent { response_type: 19, sequence: 12, event: 96468992, window: 96468992, override_redirect: false })
server (13): QueryExtension(QueryExtensionReply { sequence: 13, length: 0, present: true, major_opcode: 138, first_event: 87, first_error: 140 })
client (14): XfixesSelectSelectionInput(SelectSelectionInputRequest { window: 1970, selection: 1, event_mask: 1 })
client (15): XfixesSelectSelectionInput(SelectSelectionInputRequest { window: 1970, selection: 2, event_mask: 1 })
...

```

Both of them seems to get the `first_event` of the XFixes events (140), and call `XfixesSelectSelectionInput` with the same arguments (window + event mask). The problem is that I am not receiving the xfixes events.

After some digging, I landed in src/protocol/mod.rs, in the event parser. As far as I understand, the code:
- get the message raw bytes
- calls response_type to get the message id
- matches on "classical" messages
- if no match, test the event id against `first_event` of extension

```rust
impl Event {
    /// Parse a generic X11 event into a concrete event type.
    #[allow(clippy::cognitive_complexity, clippy::match_single_binding)]
    pub fn parse(
        event: &[u8],
        ext_info_provider: &dyn ExtInfoProvider,
    ) -> Result<Self, ParseError> {

        let event_code = response_type(event)?;
        // Check if this is a core protocol event or error, or from the generic event extension
        match event_code {
        ...

```

What puzzles me is that the `response_type` seems to only be able to respond messages between [0, 0x7f]:
```
/// Get the response type out of the raw bytes of an X11 error or event.
fn response_type(raw_bytes: &[u8]) -> Result<u8, ParseError> {
    raw_bytes.get(0)
        .map(|x| x & 0x7f)
        .ok_or(ParseError::InsufficientData)
}
```

But, as the base event of the xfixes extension here seems to be 140, I think I miss something here (as those messages won't be able to be parsed)

More over, I displayed the "raw messages" just before entering the:
```rust
        let event_code = response_type(event)?;
```

And it seems that no "special" messages seem to be retrieved which may correspond to the SelectionNotify.
Have you got any hint on the extension events reception ?

**Comment by psychon** [comment] 2021-02-17 20:27
Works for me. Here is a quick example I hacked together:
```rust
use x11rb::rust_connection::RustConnection;
use x11rb::connection::Connection;
use x11rb::protocol::xfixes::*;
use x11rb::protocol::xproto::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, _) = RustConnection::connect(None)?;
    let screen = &conn.setup().roots[0];
    conn.xfixes_query_version(100, 0)?;
    conn.xfixes_select_selection_input(
        screen.root,
        AtomEnum::PRIMARY.into(),
        SelectionEventMask::SET_SELECTION_OWNER,
    )?;
    conn.flush()?;

    loop {
        let event = conn.wait_for_event()?;
        println!("{:?}", event);
    }

    Ok(())
}
```
and here is its output (I ran the program and selected some text in some programs):
```
XfixesSelectionNotify(SelectionNotifyEvent { response_type: 87, subtype: SET_SELECTION_OWNER, sequence: 3, window: 1889, owner: 33554446, selection: 1, timestamp: 21413617, selection_timestamp: 21413617 })
XfixesSelectionNotify(SelectionNotifyEvent { response_type: 87, subtype: SET_SELECTION_OWNER, sequence: 3, window: 1889, owner: 20971544, selection: 1, timestamp: 21414881, selection_timestamp: 21414881 })
XfixesSelectionNotify(SelectionNotifyEvent { response_type: 87, subtype: SET_SELECTION_OWNER, sequence: 3, window: 1889, owner: 20971544, selection: 1, timestamp: 21414898, selection_timestamp: 21414898 })
XfixesSelectionNotify(SelectionNotifyEvent { response_type: 87, subtype: SET_SELECTION_OWNER, sequence: 3, window: 1889, owner: 20971544, selection: 1, timestamp: 21414930, selection_timestamp: 21414930 })
XfixesSelectionNotify(SelectionNotifyEvent { response_type: 87, subtype: SET_SELECTION_OWNER, sequence: 3, window: 1889, owner: 33554446, selection: 1, timestamp: 21415825, selection_timestamp: 21415825 })
```
There are just two "special things" in the code below:
- A call to `flush()` before the "main loop" to make sure that the request is actually sent (but this shouldn't be a problem with your code since you see the event being sent)
- A call to `QueryVersion` since otherwise the extension is unusable (the server just sends an error as a reply to the `SelectSelectionInput` request)

None of these two things seem to explain what you are seeing. Do you perhaps have a self-contained example reproducing the problem?

> Both of them seems to get the first_event of the XFixes events (140),

Well... no. The output is:
```
major_opcode: 138, first_event: 87, first_error: 140 }
```
The `first_event` is 87, which is way below 0x80. 140 is the first error code.

> What puzzles me is that the response_type seems to only be able to respond messages between [0, 0x7f]:

The highest bit indicates whether the event was generated by some other client via `SendEvent`. It is not part of the actual event code.

**Comment by serpilliere** [comment] 2021-02-18 09:52
Hi @psychon, thank you for the reply!
First of all, for the first point, I totally misread the `first_event` / `first_errror`, sorry for this.

Second, in the *rust* code, I didn't had the `conn.xfixes_query_version(100, 0)?;` call.
And I just tested that if I add it to the actual rust code, everything works fine and I get the XFixes notifications.

Now that you pointed it out, I see that in the C version, there was a:
```
client (7): XfixesQueryVersion(QueryVersionRequest { client_major_version: 5, client_minor_version: 0 })
```
that I missed in the Rust version.

And you are right about the error split by x11 in the case we call `SelectSelectionInput` without calling `QueryVersion`:
```
client (14): XfixesSelectSelectionInput(SelectSelectionInputRequest { window: 1970, selection: 1, event_mask: 1 })
client (15): InternAtom(InternAtomRequest { only_if_exists: false, name: [67, 76, 73, 80, 66, 79, 65, 82, 68] })
server (14): X11Error { error_kind: Request, error_code: 1, sequence: 14, bad_value: 96468992, minor_opcode: 2, major_opcode: 138 }
server (15): InternAtom(InternAtomReply { sequence: 15, length: 0, atom: 526 })
```

I just wondered why the error didn't pop in the "?" part, but I realized thar the first "?" is for the "request" and that I didn't checked the response. As the `VoidCookie` is not an error code, Rust didn't warn me that the response goes into the void. So maybe it's the same for the code you gave: in the code you gave, maybe instead of:
```rust
            conn.xfixes_select_selection_input(
                screen.root,
                AtomEnum::PRIMARY.into(),
                xfixes::SelectionEventMask::SET_SELECTION_OWNER,
            )?;
```
maybe we should do:
```rust
            conn.xfixes_select_selection_input(
                screen.root,
                AtomEnum::PRIMARY.into(),
                xfixes::SelectionEventMask::SET_SELECTION_OWNER,
            )?.check()?;
```

to be sure that the error code is tested, and there we don't need the flush right?
Thanks a lot @psychon!

**Comment by psychon** [comment] 2021-02-18 15:46
> As the VoidCookie is not an error code, Rust didn't warn me that the response goes into the void. 

Well... "half no". See this table in the docs (we have a request with a reply here): https://docs.rs/x11rb/0.8.0/x11rb/connection/index.html#handling-x11-errors

When I leave out the call to `xfixes_query_version` and run my program, it prints:
```
Error(X11Error { error_kind: Request, error_code: 1, sequence: 2, bad_value: 0, minor_opcode: 2, major_opcode: 138 }
```
So, the error doesn't go into the void, but instead is given to the main loop as an "event".

I'll close this issue since I think everything was figured out, but feel free to tell me to reopen this.

**Closed by psychon** 2021-02-18 15:46 UTC

**Comment by serpilliere** [comment] 2021-02-18 17:27
Thanks for pointing out the documentation: the error handling with the "checked" and "unchecked" cases are clear now. 
Shame on me for not having read the doc!
