### ISSUE TITLE
Failed to start connection with RustConnection

### ISSUE THREAD

**Issue by dalcde** [psychon/x11rb#204] opened 2020-02-17 20:57 UTC
I get the following error message:
```
thread 'main' panicked at 'Failed to start connection: Error { error: SetupFailed(SetupFailed { status: 0, protocol_major_version: 11, protocol_minor_version: 0, length: 6, reason: [78, 111, 32, 112, 114, 111, 116, 111, 99, 111, 108, 32, 115, 112, 101, 99, 105, 102, 105, 101, 100, 10] }) }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x55c3aa1fa86f - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55c3aa1fa86f - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55c3aa1fa86f - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55c3aa1fa86f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55c3aa1ef23c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x55c3aa1f9d06 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x55c3aa1f992e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55c3aa1f992e - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55c3aa1f992e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x55c3aa1f90d3 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x55c3aa1f90d3 - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x55c3aa1f8c4e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x55c3aa1ed9fd - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x55c3aa1ef7b6 - core::result::unwrap_failed::hca6a012bfa3eb903
                               at src/libcore/result.rs:1188
  14:     0x55c3aa1e9e9f - core::result::Result<T,E>::expect::hbb3cbfb104fec193
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:983
  15:     0x55c3aa1e9e9f - <crate>::main::h0dc740a6327e4770
                               at src/main.rs:63
  16:     0x55c3aa22ec73 - std::rt::lang_start::{{closure}}::hddbf673489d25cf9
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  17:     0x55c3aa1eae90 - main
  18:     0x7ff6ecb7a023 - __libc_start_main
  19:     0x55c3aa1e614e - _start
  20:                0x0 - <unknown>
```
The `reason` is "No protocol specified" (in ASCII). Will do some more troubleshooting later

**Comment by psychon** [comment] 2020-02-18 19:13
Two things:

1. Yay, 88e1f0b3a35a7ca3c15efb5aaf4a4f22e6b1abd1 works. Before this commit, I would expect a useless `ParseError` instead, because a `SetupFailed` cannot be parsed as a `Setup`. When trying to test this against some X11 server, I never managed to make the server reject the connection.
2. This is a duplicate of #196. Right now, `RustConnection` never sends any authentication information. This is the empty `Vec`s here:
https://github.com/psychon/x11rb/blob/a1deb7e2940ce3c2c06650c7a03bddc15a250423/src/rust_connection/mod.rs#L45
This works for me, because according to `/usr/bin/xhost`, my X11 server just uses Unix socket magic to authenticate everything coming from my user account.

According to debian codesearch, the message comes from here: https://sources.debian.org/src/xorg-server/2:1.20.7-3/os/auth.c/?hl=222#L222

I'll close this since this is a duplicate, but I would be interested in hearing more. How did you "manage" to get the X11 server to reject the connection?

Today, I took a quick look at libXau. It seems more or less doable to reimplement this in Rust (but I do not understand this XDMsomething stuff). Can you run `xauth list`? Do not paste the output, does it say `MIT-MAGIC-COOKIE-1`? If so, I might be able to implement the necessary support on the weekend.

**Closed by psychon** 2020-02-18 19:13 UTC

**Comment by dalcde** [comment] 2020-02-18 20:57
My application is a window manager and it crashes when I run `startx` with the given error message.

It either suddenly stopped working when I tried to test something (and continued to not work after I reverted), or I never actually compiled my program after I changed to `RustConnection` and it had never worked... (`startx` points directly to `target/release/<application>`, and I checked `target/debug/` is empty)

**Comment by psychon** [comment] 2020-02-19 07:04
Hm. I'm on debian testing. I just tried `startx` (starts my normal window manager) and inside of that session, `examples/simple_window` works without problems. `xhost` says that still everything from my user is allowed (and nothing else):
```
$ xhost
access control enabled, only authorized clients can connect
SI:localuser:psychon
```
Could it be that `startx` cleans up `.Xauthority` during shutdown? And that only while it is running, can some entries be found?
Anyway, my `.Xauthority` is empty, too (at least now, previously there was some content, but that must have been old, since deleting it didn't have any negative effects (so far)).

I also tried `startx /path/to/simple_window` and that works, too... :-/

Also, all my X servers are started with `-nolisten tcp`... I just started `sudo X :2` manually, and that one does not have `-nolisten tcp` in its command line, but still does not listen on tcp. Sigh.

[A while later]

Yay! `X -listen tcp :2` and then `DISPLAY=:2 xterm&` (so that the server does not reset when the last client disconnects) and `DISPLAY=:2 xhost -INET:localhost` (to remove the relevant entry from the access control list) works:
```
$ DISPLAY=127.0.0.1:2 cargo run --example simple_window --no-default-features --features vendor-xcb-proto                           rust_connection_thread:1
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s                                                                             
     Running `target/debug/examples/simple_window`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SetupFailed(SetupFailed { status: 0, protocol_major_version: 11, protocol_minor_version: 0, length: 6, reason: [78, 111, 32, 112, 114, 111, 116, 111, 99, 111, 108, 32, 115, 112, 101, 99, 105, 102, 105, 101, 100, 10] })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is the "No protocol specified" error message.

**Comment by psychon** [comment] 2020-02-19 15:52
Oh, hey. The above is totally useless. I just managed to setup a server that rejects my connections, but instead I need a server that accepts connections when the right authentication data is provided.

Wikipedia explains more: https://en.wikipedia.org/wiki/X_Window_authorization
The (for me) relevent / eye opening part is.... gone. Anyway, I remember reading somewhere that I need to start my X11 server with `-auth path-to-Xauthority-file`. And I was looking for some way to do runtime configuration....

**Comment by psychon** [comment] 2020-02-19 18:07
Okay, I figured out a working setup for testing this:
```
$ rm -f /tmp/file && xauth -f /tmp/file add :2 . 1234 && Xephyr -listen tcp -auth /tmp/file :2
$ DISPLAY=127.0.0.1:2 xterm                     
No protocol specified
xterm: Xt error: Can't open display: 127.0.0.1:2
$ DISPLAY=127.0.0.1:2 XAUTHORITY=/tmp/file xterm
^C%      
```
