### ISSUE TITLE
Event parsing into enums sometimes too strict?

### ISSUE THREAD

**Issue by andrewshadura** [psychon/x11rb#544] opened 2020-11-01 22:15 UTC
Hi,

I was porting inputplug-rust to 0.7.0 and found that while some code has been simplified by the new parsing code, not everything works as it did before. XInput Events like `XISlaveRemoved` return 0 as the type, so I had a piece of code to handle that:
```rust
if self.type_ == 0 {
    "".to_string()
} else {
    format!("XI{:?}", DeviceType::try_from(self.type_).unwrap_or_else(|_| {
        panic!("Unknown device type: {}", self.type_);
    }))
},
```
which made this output possible:
```
X Input extension opcode: 131
"/bin/true" "XISlaveAdded" "14" "XIFloatingSlave" "Logitech M325"
"/bin/true" "XIDeviceEnabled" "14" "XISlavePointer" "Logitech M325"
"/bin/true" "XIDeviceDisabled" "14" "XISlavePointer" ""
"/bin/true" "XISlaveRemoved" "14" "" ""
```
Now, I’m getting this:
```
X Input extension opcode: 131
"/bin/true" "XISlaveAdded" "14" "XIFloatingSlave" "Logitech M325"
"/bin/true" "XIDeviceEnabled" "14" "XISlavePointer" "Logitech M325"
"/bin/true" "XIDeviceDisabled" "14" "XISlavePointer" ""
Error: Failed to get an event

Caused by:
    A value could not be parsed into an enumeration
```

**Comment by andrewshadura** [comment] 2020-11-01 22:20
If you’re curious about the code, here’s the commit:
andrewshadura/inputplug-rust@897f1fcc5799f993db6e96a33962dda6cee15731

**Comment by psychon** [comment] 2020-11-02 15:53
Duplicate of #458, I think. At least that issue is also about the server sending invalid data (according to the XInput spec).
If you agree that this is a duplicate, then please close the issue.

Upstream bug report for "stop sending invalid data" is at https://gitlab.freedesktop.org/xorg/xserver/-/issues/1036.
Patch to xcb-proto to add this invalid stuff to the XML is at https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/merge_requests/13.

If you are interested in some (only half-helpful) work around, then my suggestion would be to use `wait_for_raw_event()` instead of `wait_for_event()` (there are also `raw` versions of other APIs). These then give you the moral equivalent of `Vec<u8>` instead of a parsed event. You can then try parsing those raw bytes via `conn.parse_event(event.as_ref())`.
- This allows you to handle "failed to parse an event" specially (dunno if that is worth it; you could also match on the error that is returned)
- This allows you to come up with some other parsing strategy for these events. I have no good suggestions. Bad suggestions would be to use the `xcb` crate (which means `transmute`ing the event to the right type, but there is some API in `xcb` to hide the `transmute` (uhm... does `xcb` support xinput? I'm not sure)).

Sorry, these are all my current ideas.

**Comment by andrewshadura** [comment] 2020-11-02 16:02
Hi,

> Duplicate of #458 <https://github.com/psychon/x11rb/issues/458>, I think. At least that issue is also about the server sending invalid data (according to the XInput spec).


> If you agree that this is a duplicate, then please close the issue.


You appear to be right, it's even the same part of the spec.

> If you are interested in some (only half-helpful) work around, then my suggestion would be to use `wait_for_raw_event()` instead of `wait_for_event()` (there are also `raw` versions of other APIs). These then give you the moral equivalent of `Vec<u8>` instead of a parsed event. You can then try parsing those raw bytes via `conn.parse_event(event.as_ref())`.


I'm afraid that's what I'll have to do. As far as I can see, that is the interface I used to use in <0.5.

-- 
Cheers,
  Andrej

**Comment by andrewshadura** [comment] 2020-11-04 09:32
Right, it turns out while I *can* use it, `try_from()` will still attempt to parse the enums and fail, giving me an `Err`.

**Comment by psychon** [comment] 2020-11-04 15:45
Yeah, sorry. You would have to define your own version of the struct in question, which needs a big copy&paste of the code and then replacing the enum member with an `u[correct size]`. Sorry for not being clearer here before.

**Closed** 2020-11-10 19:42 UTC
